name: iOS Build (No Tests)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14  # macOS Sonoma 對應 Xcode 16.x
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set Xcode version
      uses: actions/setup-xcode@v3
      with:
        xcode-version: '16.1'
    
    - name: Install CocoaPods
      run: |
        brew install cocoapods
        pod install
    
    - name: Build project
      run: |
        xcodebuild clean build \
          -workspace RecycledChicken.xcworkspace \
          -scheme RecycledChicken \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' \
          -quiet
