name: iOS CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app
      
      - name: Build and test
        run: |
          xcodebuild clean test -project RecycledChicken.xcodeproj -scheme RecycledChicken -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'
          
  deploy:
    name: Deploy
    needs: build
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.P12_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}
          
      - name: Install Provisioning Profile
        uses: apple-actions/download-provisioning-profiles@v1
        with:
          bundle-id: 'your.bundle.id'
          profile-type: 'IOS_APP_STORE'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          
      - name: Build App
        run: |
          xcodebuild clean archive -project RecycledChicken.xcodeproj -scheme RecycledChicken -configuration Release -archivePath build/RecycledChicken.xcarchive
          
      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath build/RecycledChicken.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build/
          
      - name: Upload to App Store
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/RecycledChicken.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }} 
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}