name: iOS Build (No Tests)
on:
  push:
    branches: [ develop ]  # 確保推送的是 'develop' 分支
  pull_request:
    branches: [ develop ]  # 確保 Pull Request 是針對 'develop' 分支
jobs:
  build:
    runs-on: macos-14  # macOS Sonoma 對應 Xcode 16.x
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.1.app
    
    - name: Install CocoaPods
      run: |
        brew install cocoapods
        pod install
    
    - name: Build project
      run: |
        xcodebuild clean build \
          -workspace RecycledChicken.xcworkspace \
          -scheme RecycledChicken \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest'
